In [1]:
import numpy as np
import pandas as pd

In [2]:
# A Pandas Series is like a column in a table.
# It is a one-dimensional array holding data.

In [3]:
my_list = [10,20,30,40,50,10]
labels = ['w','x','y','z','x1','x2']

In [4]:
var = pd.Series(data=my_list,index=labels)
print(var)

w     10
x     20
y     30
z     40
x1    50
x2    10
dtype: int64


In [5]:
var = pd.Series(data=my_list)
print(var)

0    10
1    20
2    30
3    40
4    50
5    10
dtype: int64


In [6]:
print(var)

0    10
1    20
2    30
3    40
4    50
5    10
dtype: int64


In [7]:
var[1]

20

In [8]:
#var['x']

In [9]:
type(var)

pandas.core.series.Series

In [10]:
# Arithmetic operation on series
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])

ds = ds1 + ds2
print("Add two Series:")
print(ds)

print("Subtract two Series:")
ds = ds1 - ds2
print(ds)

print("Multiply two Series:")
ds = ds1 * ds2
print(ds)

print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [11]:
print(np.random.randn(10,5))  #(Dimension of an array)

[[-0.83112441  0.30686805 -0.66811469  2.1837908  -0.50467165]
 [-0.39200154  0.2742784  -1.72223885 -0.26200186  2.42815833]
 [-0.41142286 -0.58470357  0.04037593 -0.96955525 -0.40915436]
 [-0.30075772 -1.52095466 -0.89562121 -0.22037464  0.23780474]
 [-0.53207977 -0.98193645  0.47036703 -0.4061139   0.26417276]
 [-0.59448149  1.96475299  0.88525768  0.2051531  -0.35012641]
 [-0.0230776   0.34683973  1.30565611 -0.45287553 -1.48963787]
 [-2.09064238  1.18863942 -0.22560255  0.09704905 -1.48931867]
 [-0.30210125  0.76439625  1.39835642 -0.82027674 -2.64641257]
 [ 1.58114227 -1.00500104 -0.28042904 -0.25257714 -1.79059774]]


In [12]:
print('A B C D E F')

A B C D E F


In [13]:
print('A B C D E F'.split())

['A', 'B', 'C', 'D', 'E', 'F']


## Data Frames

In [14]:
# Data Frame
#Its a 2D data structure, like a 2D array, or a table with rows and columns.

In [15]:
sample_df = pd.DataFrame(data=np.random.randn(10,5),index='A B C D E F G H I J'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())

In [16]:
sample_df

Score1    Score2    Score3    Score4    Score5
A -0.712493  0.223604  1.296586  0.410064 -2.519172
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [17]:
type(sample_df)

pandas.core.frame.DataFrame

In [18]:
var = sample_df['Score3']

In [19]:
print(var)

A    1.296586
B   -0.205839
C   -0.168979
D    0.826274
E   -1.254188
F   -1.313832
G    1.336379
H    0.115865
I    0.752655
J   -0.492477
Name: Score3, dtype: float64


In [20]:
type(var)

pandas.core.series.Series

In [21]:
var2 = sample_df[['Score3','Score5','Score4']]

In [22]:
var2

Score3    Score5    Score4
A  1.296586 -2.519172  0.410064
B -0.205839 -0.158242 -0.292270
C -0.168979 -0.827094  0.441847
D  0.826274 -0.227551  0.332132
E -1.254188 -1.829369  1.008176
F -1.313832  0.785458  0.535174
G  1.336379  0.470179  1.439481
H  0.115865  0.931541 -0.053605
I  0.752655 -1.091884  1.554568
J -0.492477 -0.283560 -0.187134

In [23]:
type(var2)

pandas.core.frame.DataFrame

In [24]:
var2.shape

(10, 3)

In [25]:
sample_df[['Score5','Score3']]

Score5    Score3
A -2.519172  1.296586
B -0.158242 -0.205839
C -0.827094 -0.168979
D -0.227551  0.826274
E -1.829369 -1.254188
F  0.785458 -1.313832
G  0.470179  1.336379
H  0.931541  0.115865
I -1.091884  0.752655
J -0.283560 -0.492477

In [26]:
sample_df['Score6'] = sample_df['Score1'] + sample_df['Score2']

In [27]:
sample_df['Score6']

A   -0.488889
B   -0.148849
C   -2.491259
D    2.798136
E   -1.423407
F    0.249621
G   -0.295262
H   -4.632146
I   -0.397717
J    0.140302
Name: Score6, dtype: float64

In [28]:
sample_df

Score1    Score2    Score3    Score4    Score5    Score6
A -0.712493  0.223604  1.296586  0.410064 -2.519172 -0.488889
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242 -0.148849
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094 -2.491259
D  2.297656  0.500479  0.826274  0.332132 -0.227551  2.798136
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369 -1.423407
F -0.408818  0.658439 -1.313832  0.535174  0.785458  0.249621
G -1.236131  0.940870  1.336379  1.439481  0.470179 -0.295262
H -2.822701 -1.809445  0.115865 -0.053605  0.931541 -4.632146
I -0.656219  0.258503  0.752655  1.554568 -1.091884 -0.397717
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560  0.140302

In [29]:
sample_df.drop('Score6',axis=1,inplace=True)

In [30]:
sample_df

Score1    Score2    Score3    Score4    Score5
A -0.712493  0.223604  1.296586  0.410064 -2.519172
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [88]:
new_df = sample_df.drop('C',axis=0,inplace=True)
#new_df = sample_df.drop(index= [0],axis=0,inplace=True)


In [32]:
new_df

In [33]:
sample_df

Score1    Score2    Score3    Score4    Score5
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [34]:
var3 = sample_df.loc[['G','H','I']]

In [35]:
var3

Score1    Score2    Score3    Score4    Score5
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884

In [36]:
type(var3)

pandas.core.frame.DataFrame

In [37]:
sample_df.iloc[3]

Score1    0.090659
Score2   -1.514066
Score3   -1.254188
Score4    1.008176
Score5   -1.829369
Name: E, dtype: float64

In [38]:
sample_df.loc['B','Score3']

-0.20583896069494323

In [39]:
sample_df.loc['F','Score5']

0.7854576497172103

In [40]:
sample_df

Score1    Score2    Score3    Score4    Score5
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [41]:
sample_df.iloc[0:2,2:4]    #(row(start,end),col(start,end))  end-1

Score3    Score4
B -0.205839 -0.292270
C -0.168979  0.441847

In [42]:
sample_df.iloc[0:,2:]

Score3    Score4    Score5
B -0.205839 -0.292270 -0.158242
C -0.168979  0.441847 -0.827094
D  0.826274  0.332132 -0.227551
E -1.254188  1.008176 -1.829369
F -1.313832  0.535174  0.785458
G  1.336379  1.439481  0.470179
H  0.115865 -0.053605  0.931541
I  0.752655  1.554568 -1.091884
J -0.492477 -0.187134 -0.283560

In [43]:
sample_df.iloc[0:,-1]

B   -0.158242
C   -0.827094
D   -0.227551
E   -1.829369
F    0.785458
G    0.470179
H    0.931541
I   -1.091884
J   -0.283560
Name: Score5, dtype: float64

In [44]:
sample_df.loc[['C','D'],['Score3','Score5']]

Score3    Score5
C -0.168979 -0.827094
D  0.826274 -0.227551

In [45]:
sample_df.iloc[4:7,2:5]

Score3    Score4    Score5
F -1.313832  0.535174  0.785458
G  1.336379  1.439481  0.470179
H  0.115865 -0.053605  0.931541

In [46]:
sample_df.loc[['E','F','G'],['Score4','Score3','Score5']]

Score4    Score3    Score5
E  1.008176 -1.254188 -1.829369
F  0.535174 -1.313832  0.785458
G  1.439481  1.336379  0.470179

In [47]:
sample_df

Score1    Score2    Score3    Score4    Score5
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [48]:
p1 = sample_df.iloc[2,3]
p1

0.3321315475392956

In [49]:
p2 = sample_df.iloc[[2,3]]
p2

Score1    Score2    Score3    Score4    Score5
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369

In [50]:
sample_df

Score1    Score2    Score3    Score4    Score5
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [51]:
sample_df > 0.5

Score1  Score2  Score3  Score4  Score5
B   False   False   False   False   False
C   False   False   False   False   False
D    True    True    True   False   False
E   False   False   False    True   False
F   False    True   False    True    True
G   False    True    True    True   False
H   False   False   False   False    True
I   False   False    True    True   False
J   False   False   False   False   False

In [52]:
sample_df[sample_df > 0.5]

Score1    Score2    Score3    Score4    Score5
B       NaN       NaN       NaN       NaN       NaN
C       NaN       NaN       NaN       NaN       NaN
D  2.297656  0.500479  0.826274       NaN       NaN
E       NaN       NaN       NaN  1.008176       NaN
F       NaN  0.658439       NaN  0.535174  0.785458
G       NaN  0.940870  1.336379  1.439481       NaN
H       NaN       NaN       NaN       NaN  0.931541
I       NaN       NaN  0.752655  1.554568       NaN
J       NaN       NaN       NaN       NaN       NaN

In [53]:
sample_df

Score1    Score2    Score3    Score4    Score5
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [54]:
sample_df[sample_df['Score1'] > 0.5]

Score1    Score2    Score3    Score4    Score5
D  2.297656  0.500479  0.826274  0.332132 -0.227551

In [55]:
sample_df[sample_df['Score1']>0.5]['Score1']

D    2.297656
Name: Score1, dtype: float64

In [56]:
sample_df[sample_df['Score1']>0.5][['Score3','Score5','Score4']]

Score3    Score5    Score4
D  0.826274 -0.227551  0.332132

In [57]:
sample_df

Score1    Score2    Score3    Score4    Score5
B  0.110221 -0.259070 -0.205839 -0.292270 -0.158242
C -2.302443 -0.188816 -0.168979  0.441847 -0.827094
D  2.297656  0.500479  0.826274  0.332132 -0.227551
E  0.090659 -1.514066 -1.254188  1.008176 -1.829369
F -0.408818  0.658439 -1.313832  0.535174  0.785458
G -1.236131  0.940870  1.336379  1.439481  0.470179
H -2.822701 -1.809445  0.115865 -0.053605  0.931541
I -0.656219  0.258503  0.752655  1.554568 -1.091884
J -0.188822  0.329125 -0.492477 -0.187134 -0.283560

In [58]:
sample_df[(sample_df['Score2'] > 0.5) & (sample_df['Score3'] > 0.2)][['Score2','Score3']]

Score2    Score3
D  0.500479  0.826274
G  0.940870  1.336379

In [59]:
sample_df[(sample_df['Score1']>0.5) | (sample_df['Score3'] > 0.2)][['Score3','Score4']]

Score3    Score4
D  0.826274  0.332132
G  1.336379  1.439481
I  0.752655  1.554568

# Missing Val

In [60]:
sports_data = {'Cricket':[1,2,np.nan, 4,6,7],'Tennis':[5,np.nan,2,np.nan,4,7] }

In [61]:
sports_df = pd.DataFrame(sports_data)

In [62]:
sports_df

Cricket  Tennis
0      1.0     5.0
1      2.0     NaN
2      NaN     2.0
3      4.0     NaN
4      6.0     4.0
5      7.0     7.0

In [63]:
type(sports_df)

pandas.core.frame.DataFrame

In [64]:
sports_df['Cricket'] = sports_df['Cricket'].fillna(value=sports_df['Cricket'].median())

In [65]:
sports_df['Cricket'] = sports_df['Cricket'].fillna(value=10)

In [66]:
sports_df['Tennis'] = sports_df['Tennis'].fillna(value=sports_df['Tennis'].mean())

In [67]:
sports_df

Cricket  Tennis
0      1.0     5.0
1      2.0     4.5
2      4.0     2.0
3      4.0     4.5
4      6.0     4.0
5      7.0     7.0

In [89]:
# Read and Write operations
import pandas as pd
mydataset = {
  'Height': [5.5,5,6,7,5.4,7,6.1,5.6,6.4,5.7],
  'Weight': [50,56,67,73,63,80,53,72,59,62]
}
df = pd.DataFrame(mydataset)
print(df)

   Height  Weight
0     5.5      50
1     5.0      56
2     6.0      67
3     7.0      73
4     5.4      63
5     7.0      80
6     6.1      53
7     5.6      72
8     6.4      59
9     5.7      62


In [90]:
# Write csv,excel and json
df.to_csv('sample.csv')
df.to_excel('sample.xls')
df.to_json('d1.json')

In [93]:
df3=pd.read_csv('sample.csv')

In [95]:
df3.to_excel('sample1.xls')

In [91]:
# Read Excel
df1=pd.read_excel('sample.xls')

In [92]:
df1

Unnamed: 0  Height  Weight
0           0     5.5      50
1           1     5.0      56
2           2     6.0      67
3           3     7.0      73
4           4     5.4      63
5           5     7.0      80
6           6     6.1      53
7           7     5.6      72
8           8     6.4      59
9           9     5.7      62

In [72]:
# Reading json file
dfj=pd.read_json('d1.json')

In [73]:
dfj

Height  Weight
0     5.5      50
1     5.0      56
2     6.0      67
3     7.0      73
4     5.4      63
5     7.0      80
6     6.1      53
7     5.6      72
8     6.4      59
9     5.7      62

In [74]:
#read the dataset
df=pd.read_csv('heart.csv')


In [75]:
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [76]:
df.head(2)  

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   

   caa  thall  output  
0    0      1       1  
1    0      2       1

In [77]:
df.tail(1)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
302    1      2       0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [79]:
df.shape

(303, 14)

In [80]:
df.describe()

age         sex          cp      trtbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg    thalachh        exng     oldpeak         slp         caa  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

            thall      output  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [81]:
df.isnull()

age    sex     cp  trtbps   chol    fbs  restecg  thalachh   exng  \
0    False  False  False   False  False  False    False     False  False   
1    False  False  False   False  False  False    False     False  False   
2    False  False  False   False  False  False    False     False  False   
3    False  False  False   False  False  False    False     False  False   
4    False  False  False   False  False  False    False     False  False   
..     ...    ...    ...     ...    ...    ...      ...       ...    ...   
298  False  False  False   False  False  False    False     False  False   
299  False  False  False   False  False  False    False     False  False   
300  False  False  False   False  False  False    False     False  False   
301  False  False  False   False  False  False    False     False  False   
302  False  False  False   False  False  False    False     False  False   

     oldpeak    slp    caa  thall  output  
0      False  False  False  False   False  
1      False  False  False  False   False  
2      False  False  False  False   False  
3      False  False  False  False   False  
4      False  False  False  False   False  
..       ...    ...    ...    ...     ...  
298    False  False  False  False   False  
299    False  False  False  False   False  
300    False  False  False  False   False  
301    False  False  False  False   False  
302    False  False  False  False   False  

[303 rows x 14 columns]

In [82]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64